AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
